In [3]:
import numpy as np

## Q#1: Create x array with elements equal to 1.

In [4]:
x = np.ones((2,2))
x

array([[1., 1.],
       [1., 1.]])

## Q#2: Create y array with elements equal to 0.

In [5]:
y = np.zeros((2, 2))
y

array([[0., 0.],
       [0., 0.]])

## Q#3: Add x and y arrays.

In [6]:
np.add(x, y) 

array([[1., 1.],
       [1., 1.]])

## Q#4: Print x array characteristics (e.g: dimension, shape, size, type)

In [7]:
print('type = ', x.dtype)
print('number of dimensions = ', x.ndim)
print('shape = ', x.shape)
print('size = ', x.size)

type =  float64
number of dimensions =  2
shape =  (2, 2)
size =  4


## Q#5: Create a 2D array "called w" as the following:

|       |          |
| ----- | -------- |
| 11    | 12       |
| 13    | 14       |
| 15    | 16       |


In [8]:
w = np.array([[11, 12], [13, 14] , [15,16]])
w

array([[11, 12],
       [13, 14],
       [15, 16]])

## Q#6: Create z array contains the numbers from 1 to 3.

In [9]:
z = np.arange(1,3)
z

array([1, 2])

## Q#7: Combine the arrays z and w in vertical way then save it in a new variable "newArray".

In [10]:
newArray = np.vstack((w, z))
newArray

array([[11, 12],
       [13, 14],
       [15, 16],
       [ 1,  2]])

## Q#8: Print all elements of "newArray" using the loop.

In [11]:
for item in newArray.flat:
    print(item)
    


11
12
13
14
15
16
1
2


## Q#9: Reverse the columns and rows of "newArray".

In [12]:
newArray.transpose()

array([[11, 13, 15,  1],
       [12, 14, 16,  2]])

## Q#10: Decrement all elements of "newArray" with 1.

In [13]:
newArray -= 1
newArray

array([[10, 11],
       [12, 13],
       [14, 15],
       [ 0,  1]])

## Q#11: Find smallest and biggest values in "newArray".

In [14]:
#smallest values
newArray.min()

0

In [15]:
#biggest values
newArray.max()

15

## Q#12: Print the first row of "newArray" using indexing.

In [16]:
newArray[0]

array([10, 11])

## Q#13: Print the number equals 12 of "newArray" using indexing.

In [17]:
newArray[1, 0]

12

## Q#14: Print the numbers equal 0 and 13 of "newArray" using Slicing.

In [30]:
newArray[1:2 ,1 ]

array([13])

In [31]:
newArray[3: ,0 ]

array([0])

## Q#15: Change the shape of "newArray" to (9,1).

In [33]:
newArray.shape = (9, 1)
#cannot reshape array of size 8 into shape (9,1)
#size < 9

ValueError: cannot reshape array of size 8 into shape (9,1)

## Q#16: Change the shape of "newArray" to (3,2).

In [35]:
newArray.reshape(3, 2)
#cannot reshape array of size 8 into shape (3,2)
#size > 6

ValueError: cannot reshape array of size 8 into shape (3,2)

# Well Done 🎉